# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'd4tagirl'
tagline:          'Daniela Vazquez'
description:      'A Blog about my random Data Science projects'
meta_description: 'I''m Daniela Vazquez and this is my blog where I plan to share my Data Science projects. I''m particularly interested in Machine Learning and the R Programming Language'
meta_tags:        ['blog', 'r', 'rstats', 'data science', 'daniela vazquez', 'RLadies', 'NASA Datanaut', 'machine learning']
url:              https://d4tagirl.com
baseurl:          /

author:
  name:           'Daniela Vazquez'
  url:            https://twitter.com/intent/tweet?user_id=114258616
  email:          daniela.vazquez@gmail.com

paginate:         30
excerpt_separator: <!--more-->

extlinks:
  attributes: {rel: nofollow, target: _blank}
#  check_links: true
  check_exclude: ['twitter.com', 'disqus.com']
#  rel_exclude: ['host1.com', 'host2.net']

page_gen:
  - data: tags
    template: tag
    name: tag
    dir: tags

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]
