# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'd4tagirl'
tagline:          'Daniela Vazquez'
description:      'Blog about Data Science, Machine Learning, R and other personal projects'
meta_description: ""
meta_tags:        ['blog', 'r', 'data science', 'daniela vazquez']
url:              https://d4tagirl.com
baseurl:          /

author:
  name:           'Daniela Vazquez'
  url:            https://twitter.com/intent/tweet?user_id=114258616

paginate:         30
excerpt_separator: <!--more-->

extlinks:
  attributes: {rel: nofollow, target: _blank}
#  check_links: true
  check_exclude: ['twitter.com', 'disqus.com']
#  rel_exclude: ['host1.com', 'host2.net']

page_gen:
  - data: tags
    template: tag
    name: tag
    dir: tags

# Custom vars
version:          2.1.0
gems: [jekyll-paginate]
